# Generated by Django 3.1.2 on 2020-10-12 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_title', models.CharField(max_length=50)),
                ('Post_pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Post_text', models.TextField(max_length=300)),
                ('Post_image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
